Feature/efficient delta e (まだマージしなくてOKです)
OpenJij/OpenJij pull request #157
Opened 2020-09-30 13:55 UTC by yuyamashiro

一旦プルリク投げておきます。
エネルギー差分の計算アルゴリズムをSAだけ変更しました。
Sparseだとだいぶ計算がきついです。ここの原因チェックした方が良いかもしれません。

2020-09-30 23:47 UTC, j-i-k-o requested changes

2020-09-30 23:47 UTC, j-i-k-o commented on src/updater/single_spin_flip.hpp
> +                        system.dE(index) *= -1;
モンテカルロステップの最後で `system.spin(system.num_spins) = 1;` していますが、この際`system.dE(index) *= -1;`に相当する計算を行わなければならないはずなので `dE`の値が整合していないと思います。縦磁場をいれると結果が怪しくなる可能性があります。

2020-09-30 23:47 UTC, j-i-k-o commented on src/updater/single_spin_flip.hpp
> +                for (std::size_t index = 0; index < system.num_spins; ++index) {
`for (std::size_t index = 0; index < system.num_spins-1; ++index) {`
が良いと思います。理由は下にあります。

2020-09-30 23:49 UTC, yuyamashiro commented on src/updater/single_spin_flip.hpp
> +                        system.dE(index) *= -1;
なるほど確かにです。見逃していました。

2020-09-30 23:50 UTC, yuyamashiro commented on src/updater/single_spin_flip.hpp
> +                for (std::size_t index = 0; index < system.num_spins; ++index) {
最後のスピンについては磁場を表現する補助スピンだからですね。了解です。

2020-10-02 04:19 UTC, j-i-k-o commented on src/updater/single_spin_flip.hpp
> +                for (std::size_t index = 0; index < system.num_spins; ++index) {
今見ていたら、そもそも `system.num_spins`が補助スピンを加える前のスピン数を表現していたので、これ直さなくて大丈夫なやつでした。

2020-10-14 05:38 UTC, j-i-k-o approved these changes

2020-10-14 06:53 UTC, merged