Adapted to multiple architectures.
OpenJij/OpenJij pull request #188
Opened 2021-07-14 05:57 UTC by 29rou

Apple Siliconやlinux/arm64へ対応したビルドを可能にした。

2021-07-14 13:54 UTC, 29rou commented
https://github.com/29rou/OpenJij/actions/runs/1030478513

2021-07-15 01:31 UTC, j-i-k-o commented
Python 3.8.2 (default, Jun  8 2021, 11:59:35) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import openjij as oj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/openjij/__init__.py", line 4, in <module>
    from .sampler import Response
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/openjij/sampler/__init__.py", line 2, in <module>
    from .sampler import *
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/openjij/sampler/sampler.py", line 19, in <module>
    import cxxjij
ImportError: dlopen(/Users/xxx/Library/Python/3.8/lib/python/site-packages/cxxjij.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/xxx/Library/Python/3.8/lib/python/site-packages/cxxjij.cpython-38-darwin.so
  Reason: image not found
>>>

2021-07-15 01:33 UTC, j-i-k-o commented
↑が出てmacではimport時にエラーが発生しますね...

2021-07-16 05:01 UTC, 29rou commented
https://github.com/29rou/OpenJij/actions/runs/1036303177

2021-07-19 07:02 UTC, j-i-k-o requested changes
@29rou 手元で `python setup.py test`を試してみたところ(CUDA有効化)、以下のようなエラーが出るようです。
```sh
❯ python setup.py test
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'version_config'
  warnings.warn(msg)
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing openjij.egg-info/PKG-INFO
writing dependency_links to openjij.egg-info/dependency_links.txt
writing requirements to openjij.egg-info/requires.txt
writing top-level names to openjij.egg-info/top_level.txt
adding license file 'LICENSE' (matched pattern 'LICENSE')
reading manifest file 'openjij.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cmake'
warning: no files found matching 'FetchContent/*.cmake.in'
writing manifest file 'openjij.egg-info/SOURCES.txt'
running build_ext
Linux
-- OMP_FOUND = YES
-- USE_OMP = Yes
-- USE_CUDA = Yes
-- USE_TEST = OFF
-- Skip downloding googletest
-- pybind11 v2.6.2 
CMake Error at openjij/CMakeLists.txt:32 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "cxxjij".  All uses of target_link_libraries with a target must
  be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * openjij/CMakeLists.txt:18 (target_link_libraries)



-- Configuring incomplete, errors occurred!
See also "/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeOutput.log".
See also "/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/setup.py", line 169, in <module>
    setup(
  File "/home/jiko/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/setup.py", line 150, in run
    super(GoogleTestCommand, self).run()
  File "/home/jiko/.local/lib/python3.9/site-packages/setuptools/command/test.py", line 231, in run
    with self.project_on_sys_path():
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/jiko/.local/lib/python3.9/site-packages/setuptools/command/test.py", line 150, in project_on_sys_path
    self.run_command('build_ext')
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/setup.py", line 49, in run
    self.build_extension(ext)
  File "/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/setup.py", line 132, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/jiko/workspace/Jij/openjij/pullreq/OpenJij', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

おそらく`openjij/CMakeLists.txt`の18行目の
```cmake
target_link_libraries(cxxjij 
        ${CUDA_LIBRARIES} ${CUDA_curand_LIBRARY} ${CUDA_CUBLAS_LIBRARIES} 
        cxxjij_chimera_gpu_kernel_static
    )
```
をする際に、その後の箇所の`target_link_libraries`でPRIVATE指定されているのが原因かと思われます。

2021-07-19 07:06 UTC, j-i-k-o commented
↑の18行目を抜いて実行してみましたが、
```sh
❯ python setup.py test
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'version_config'
  warnings.warn(msg)
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing openjij.egg-info/PKG-INFO
writing dependency_links to openjij.egg-info/dependency_links.txt
writing requirements to openjij.egg-info/requires.txt
writing top-level names to openjij.egg-info/top_level.txt
adding license file 'LICENSE' (matched pattern 'LICENSE')
reading manifest file 'openjij.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cmake'
warning: no files found matching 'FetchContent/*.cmake.in'
writing manifest file 'openjij.egg-info/SOURCES.txt'
running build_ext
Linux
-- OMP_FOUND = YES
-- USE_OMP = Yes
-- USE_CUDA = Yes
-- USE_TEST = OFF
-- Skip downloding googletest
-- pybind11 v2.6.2 
-- Configuring done
CMake Warning (dev) in src/system/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cxxjij_chimera_gpu_kernel".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/system/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cxxjij_chimera_gpu_kernel".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/system/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cxxjij_chimera_gpu_kernel".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/system/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cxxjij_chimera_gpu_kernel_static".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/system/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "cxxjij_chimera_gpu_kernel_static".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9
/home/jiko/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -S/home/jiko/workspace/Jij/openjij/pullreq/OpenJij -B/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9 --check-build-system CMakeFiles/Makefile.cmake 0
/home/jiko/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E cmake_progress_start /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/CMakeFiles /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9//CMakeFiles/progress.marks
/usr/bin/make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9'
/usr/bin/make  -f src/system/CMakeFiles/cxxjij_chimera_gpu_kernel.dir/build.make src/system/CMakeFiles/cxxjij_chimera_gpu_kernel.dir/depend
make[2]: Entering directory '/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9'
cd /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9 && /home/jiko/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E cmake_depends "Unix Makefiles" /home/jiko/workspace/Jij/openjij/pullreq/OpenJij /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/src/system /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9 /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/src/system /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/src/system/CMakeFiles/cxxjij_chimera_gpu_kernel.dir/DependInfo.cmake --color=
Scanning dependencies of target cxxjij_chimera_gpu_kernel
make[2]: Leaving directory '/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9'
/usr/bin/make  -f src/system/CMakeFiles/cxxjij_chimera_gpu_kernel.dir/build.make src/system/CMakeFiles/cxxjij_chimera_gpu_kernel.dir/build
make[2]: Entering directory '/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9'
[ 14%] Building CUDA object src/system/CMakeFiles/cxxjij_chimera_gpu_kernel.dir/gpu/chimera_cuda/kernel.cu.o
cd /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/src/system && /opt/cuda/bin/nvcc -forward-unknown-to-host-compiler -DEIGEN_DONT_PARALLELIZE -DUSE_CUDA -DUSE_OMP -Dcxxjij_chimera_gpu_kernel_EXPORTS -I/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/src -I/usr/include/eigen3 -I/opt/cuda/targets/x86_64-linux/include -O3 -DNDEBUG -Xcompiler=-fPIC -std=c++11 -x cu -dc /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/src/system/gpu/chimera_cuda/kernel.cu -o CMakeFiles/cxxjij_chimera_gpu_kernel.dir/gpu/chimera_cuda/kernel.cu.o
[ 28%] Linking CUDA device code CMakeFiles/cxxjij_chimera_gpu_kernel.dir/cmake_device_link.o
cd /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/src/system && /home/jiko/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cxxjij_chimera_gpu_kernel.dir/dlink.txt --verbose=1
/opt/cuda/bin/nvcc -forward-unknown-to-host-compiler -O3 -DNDEBUG -Xcompiler=-fPIC -Wno-deprecated-gpu-targets -shared -dlink CMakeFiles/cxxjij_chimera_gpu_kernel.dir/gpu/chimera_cuda/kernel.cu.o -o CMakeFiles/cxxjij_chimera_gpu_kernel.dir/cmake_device_link.o   /opt/cuda/lib64/libcudart_static.a -ldl -lpthread -lcudadevrt -lcudart_static -lrt 
[ 42%] Linking CUDA shared library ../../../../libcxxjij_chimera_gpu_kernel.so
cd /home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9/src/system && /home/jiko/.local/lib/python3.9/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cxxjij_chimera_gpu_kernel.dir/link.txt --verbose=1
/opt/cuda/bin/g++ -fPIC -shared -Wl,-soname,libcxxjij_chimera_gpu_kernel.so -o ../../../../libcxxjij_chimera_gpu_kernel.so CMakeFiles/cxxjij_chimera_gpu_kernel.dir/gpu/chimera_cuda/kernel.cu.o CMakeFiles/cxxjij_chimera_gpu_kernel.dir/cmake_device_link.o  /opt/cuda/lib64/libcurand.so /opt/cuda/lib64/libcublas.so /opt/cuda/lib64/libcudart_static.a -ldl /usr/lib/librt.so -lpthread /usr/lib/libgomp.so /usr/lib/libpthread.so -lcudadevrt -lcudart_static -lrt -lpthread -ldl  -L"/opt/cuda/targets/x86_64-linux/lib/stubs" -L"/opt/cuda/targets/x86_64-linux/lib"
make[2]: Leaving directory '/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/build/temp.linux-x86_64-3.9'
[ 42%] Built target cxxjij_chimera_gpu_kernel
/usr/bin/make  -f src/system/CMakeFiles/cxxjij_chimera_gpu_kernel_static.dir/build.make src/system/CMakeFiles/cxxjij_chimera_gpu_kernel_static.dir/depend
make[2]: Entering directory '/home/jiko/workspace/Jij/openjij/pullreq/OpenJij/ [...]

2021-07-19 07:53 UTC, j-i-k-o commented
また、cmakeに`USE_TEST`オプションを追加してもらえると、C++コードのテストも動作するので、そちらもお願いしたいです。

2021-07-19 08:37 UTC, 29rou commented
これは```target_link_libraries```が重複して定義されているためですね。
https://github.com/OpenJij/OpenJij/pull/188#pullrequestreview-709211022

2021-07-19 09:52 UTC, 29rou commented
Github Actionsで```USE_TEST```を有効にしました。
https://github.com/29rou/OpenJij/actions/runs/1044738928

2021-07-20 05:11 UTC, j-i-k-o approved these changes

2021-07-20 05:11 UTC, merged