Feature/translate
OpenJij/OpenJij pull request #332
Opened 2022-11-02 14:44 UTC by mei-maruo

## Changes

- Translated 000-intro intro_optimization_and_Ising.ipynb into English.

## Related issue

- N/A

## Sample code

- [OpenJij](https://github.com/OpenJij/OpenJij)/[docs](https://github.com/OpenJij/OpenJij/tree/main/docs)/[tutorial](https://github.com/OpenJij/OpenJij/tree/main/docs/tutorial)/[ja](https://github.com/OpenJij/OpenJij/tree/main/docs/tutorial/ja)/000-intro_optimization_and_Ising.ipynb

## Destructive changes

- N/A

## Misc

2022-11-07 08:04 UTC, Jacomichi requested changes

2022-11-08 17:40 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "# 0-Introduction: Combinatorial optimization and the Ising model\n",
消しました。

2022-11-08 17:40 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "In this note, we will discuss combinatorial optimization computation using the Ising model, but various other algorithms have been studied in the context of combinatorial optimization computatio
消しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "The Hamiltonian $H$ of the Ising model is written as follows:\n",
修正しました。合わせて、日本語版も$H$を$H_J$にしておきました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "The $J_{ij}$ represents the strength of the bond between the spins, and $h_i$ represents the strength of the property that each spin wants to take either 1 or -1.\n",
修正しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "The value of the cost function of the new spin configuration, $H(\\vec{\\sigma}_\\mathrm{new})$, is calculated and if the value of the cost function is reduced by even a small amount, the new sp
修正しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/001-openjij_introduction.ipynb
> +    "# 1-Introduction to OpenJij\n",
消しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/001-openjij_introduction.ipynb
> +      "Location: /Users/maruomei/miniconda3/envs/jij/lib/python3.10/site-packages\n",
Atomから直接名前の部分を消して、ノートから表示が消えたことを確認しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/001-openjij_introduction.ipynb
> +    "First, we prepare $H_I$ and $J_{ij}$ as input data.\n",
修正しました。（下と併せて2箇所）

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/001-openjij_introduction.ipynb
> +    "Above we passed $H_i$ and $J_{ij}$ as dictionaries, but NumPy-based input can be more convenient with huge problems.\n",
上記と併せて修正しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/001-openjij_introduction.ipynb
> +    "When solving a real problem in society, it is often more straightforward to formulate the problem into a form called QUBO (Quadratic unconstrained binary optimization) than to the Ising model.\n
修正しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/001-openjij_introduction.ipynb
> +    "There are other ways to take $\\sum, Q_{ij}$ (e.g. let $Q_{ij}$ a symmetric matrix), but let us formulate it as above.\n",
- 日本語版、英語版ともに文章を修正しました。
- 日本語版、英語版ともに$\sum, Q_{ij}$を$\sum Q_{ij}$に修正しました。

2022-11-08 17:41 UTC, mei-maruo commented on docs/tutorial/en/001-openjij_introduction.ipynb
> +    "As mentioned above, when solving a problem, the longitudinal magnetic fields and the interaction coefficients are set as variables and substituted, as in `.sample_ising(h, J)`.\n",
修正しました。

2022-11-11 07:33 UTC, Jacomichi approved these changes

2022-12-13 22:52 UTC, 29rou approved these changes

2022-12-20 12:56 UTC, maqid commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "$$H = \\sum_{ijt}d_{ij}q_{it}q_{j(t+1)} + \\sum_t A_t(\\sum_i q_{it} - 1)^2 + \\sum_i B_i(\\sum_t q_{it} - 1)^2$$\n",
modが抜けているので上記の表現と合わせた方がいいように思います。
$$\sum_{ijt}d_{ij}q_{it}q_{j(t+1)\mod n} + \\sum_t A_t(\\sum_i q_{it} - 1)^2 + \\sum_i B_i(\\sum_t q_{it} - 1)^2$$
（\sum_{ijt}d_{ij}q_{it}q_{j(t+1)\mod n} + \\sum_t A_t(\\sum_i q_{it} - 1)^2 + \\sum_i B_i(\\sum_t q_{it} - 1)^2）

2022-12-20 12:56 UTC, maqid commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "$$H = \\sum_{ijt}d_{ij}q_{it}q_{j(t+1)} + \\sum_t A_t(\\sum_i q_{it} - 1)^2 + \\sum_i B_i(\\sum_t q_{it} - 1)^2$$\n",
細かいですが、文脈的には$H_Q$ですかね？

2022-12-20 19:37 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "$$H = \\sum_{ijt}d_{ij}q_{it}q_{j(t+1)} + \\sum_t A_t(\\sum_i q_{it} - 1)^2 + \\sum_i B_i(\\sum_t q_{it} - 1)^2$$\n",
HをH_Qに修正しました。

2022-12-20 19:37 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "$$H = \\sum_{ijt}d_{ij}q_{it}q_{j(t+1)} + \\sum_t A_t(\\sum_i q_{it} - 1)^2 + \\sum_i B_i(\\sum_t q_{it} - 1)^2$$\n",
修正しました。

2022-12-20 19:38 UTC, mei-maruo commented on docs/tutorial/en/000-intro_optimization_and_Ising.ipynb
> +    "$$\\sum_{ijt}d_{ij}q_{it}q_{j(t+1)} \\mod n$$\n",
修正しました。

2022-12-21 01:19 UTC, maqid approved these changes

2023-01-10 07:14 UTC, merged