Feature/translate 002
OpenJij/OpenJij pull request #334
Opened 2022-11-04 06:13 UTC by mei-maruo

## Changes

- Translated 002-HuboSolver.ipynb into English.

## Related issue

- N/A

## Sample code

- [https://github.com/OpenJij/OpenJij/blob/main/docs/tutorial/ja/002-HuboSolver.ipynb](https://github.com/OpenJij/OpenJij/blob/main/docs/tutorial/ja/002-HuboSolver.ipynb)

## Destructive changes

- N/A

## Misc

- Added minor detail on the magnitude of the interaction coefficient

2022-11-09 02:55 UTC, K-Suzuki-Jij requested changes
英訳ありがとうございます。

気になる部分をコメントしましたが、こちらの英語が不適切な場合もあると思うので、おかしな依頼や英文を提案していたら私の提案文章を修正していただいてかまいません。
元の日本語版の書き方がそもそも良くない部分もあり、単純な翻訳以上の修正を依頼してしまう点、申し訳ないです。よろしくお願いします。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Here, the penalty strength set to 5.0 is the penalty for the constraint conditions that arise when converting higher-order interactions to second-order or lower-order interactions. When it is to
> In practice, it is difficult to determine how much value to specify, but here we set the value to 5.0."

In practice, it is difficult to determine how much value to specify.で文を切って、5.0に設定したのは簡単のためというニュアンスなので、butはとるか、for simplicityとかにしてほしいです。

OpenJijは
`!pip install openjij`
という段落があるので、dimodも
`!pip install dimod`
というセルをつけるのはどうでしょうか？

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "We want to solve this QUBO with OpenJij's SA, but since OpenJij cannot handle variables that are a mixture of numbers and strings, we need to convert all strings to integers.\n",
> OpenJij's SA

SAという単語がここで初出なきがしますが、以前にSimurated Annealingという単語は出てきているので、そこで括弧でSAという表記を入れておいてほしいです。または、OpenJij's simurated annealingと全部書いてもいいとおもいます。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "To do so, we use dimod's method label_variables to convert \"1∗2\" and \"aux1,2\" to integers."
> To do so

これは少し口語的かなという印象を受けましたがいかがでしょうか？もう少し硬い語にしてほしいです。

> dimod's method label_variables

メソッド名はrelabel_variablesです。あと、以下のリンクを張っていただきたいです。
https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.SampleSet.relabel_variables.html

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "All indices have been converted to integers, and we can solve this QUBO using OpenJij."
> All indices

前の文章ではindexの複数形としてindexesを使っていましたが、使い分けは適切でしょうか？(純粋に分かってないのでただの質問です。これで正しければこのままでお願いします。)

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "The energy obtained here may not correspond to the original energy of HUBO, depending on the value of strength determined earlier.\n",
> the value of strength determined earlier.

the value of penalty strength set by 5.0 earlier.などにしてほしいです。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "This can be verified with dimod's ExactPolySolver, which is a solver for exact optimal solutions."
> dimod's ExactPolySolver

ここに以下のリンクを張っていただきたいです。
https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/sampler_composites/higher_order_samplers.html#dimod.reference.samplers.ExactPolySolver

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "## Comparing the results of direct HUBO solving and indirect HUBO solving\n",
> Comparing the results of direct HUBO solving and indirect HUBO solving

長いので、Comparing the results of direct and indirect HUBO solvingに変えてほしいです。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "First, we obtain the energy when using the sample_HUBO method."
> sample_HUBO

sample_huboでお願いします。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Next, we find the energy by solving using the QUBO transformation.\n",
> by solving using the QUBO transformation.

solvingはなくていいと思います。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "As before, we will perform 100 SAs and compare the energies obtained. The strength for the QUBO conversion is set to 2."
> QUBO conversion

明確な使い分けがなければ、QUBO transformationかQUBO conversionどちらかに統一したいです。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "We can see that there is quite a difference in this model: solving directly for HUBO yields a lower energy solution.\n",
> solving directly for HUBO

forはいらないと思います。

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Of course, a more appropriate value of strength could improve the solution by solving for the QUBO transformation, but that is not easy to do."
> by solving for the QUBO transformation

ここのforはusingやthroughの方が適切ではないでしょうか？

2022-11-09 02:55 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "The solution method using the QUBO transformation requires preprocessing to convert to QUBO and to determine a parameter called strength.\n",
> called strength

わかりやすさのためにstrengthではなくpenalty strengthに統一したいです。

2022-11-15 20:00 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Let us consider a model that introduces a higher-order term compared to the usual Ising model. Specifically, we introduce the following energy function for the binary variables $\\sigma_{i} \\in
Let us introduce a model with higher-order terms added to the ordinary Ising model.
Specifically, we consider the following energy function for the binary variables $\sigma_{i} \in \{-1, +1\}$ or $\sigma_{i} \in \{0, 1\}$:
に変更しました。

2022-11-15 20:00 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "where the subscript $i,j,k,\\ldots$ are indexes that specify binary variables and take the value of $1\\leq i,j,k,\\dots \\leq N$. The $c$ is a constant and corresponds to a zero-order term.\n",
The subscripts $i,j,k,\ldots$ are indices that specify binary variables and take the value of $1\leq i,j,k,\dots \leq N$, and $c$ represents a constant value that corresponds to a zero-order term.
に変更しました。

2022-11-15 20:00 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "The problem of finding the pair of variables $(\\sigma_{1}, \\sigma_{2}, \\ldots, \\sigma_{N})$ that gives the minimum value of this energy function is called higher-order unconstrained binary o
finding variablesとしました。

2022-11-15 20:00 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "This type of problem can be regarded as a natural extension of the usual Ising model and appears in fields such as quantum chemistry.\n",
This type of problem can be regarded as a natural extension of the ordinary Ising model and appears in quantum chemistry.
としました。

2022-11-15 20:00 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "## Definition of HUBO\n",
上記のように変更しました。

2022-11-15 20:00 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "In this tutorial, for simplicity, we will consider the problem of $N=3$ variables in which only terms of third-order or lower appear as follows. In the following, variables are assumed to be spi
For simplicity, we can assume that the problem will only consist of third-order or lower terms with N=3 variables.
と
Here we assume that $\sigma_i \in \\{-1,+1\}$ is spin variable.
に変更しました。

2022-11-15 20:00 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "To solve this problem in OpenJij, we first represent this energy function interaction $h_i, J_{ij}, K_{ijk}$ in python dictionary type.\n",
To solve this problem using OpenJij, we first represent the interaction $h_i, J_{ij}, K_{ijk}$ appeared in this energy function to be in python dictionary type.
と変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Normally, when solving HUBO, QUBO is generated by reducing the order of the interaction to second-order or lower and then solving it.\n",
上記のように変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "As interaction coefficients are specified for the Ising model, we set the key of the dictionary-type to the index specifying the spin variable involved in the interaction, and the value to the v
As the following code shows, we set the index specifying spin variables to the key of the dictionary-type, and the interaction to the value.
に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "For example, ('a', 'b'): -1 means that the magnitude of the interaction coefficient between spin a and spin b is -1."
上記のように変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "To generate the corresponding QUBO from the third-order interaction, we use D-Wave's dimod library.\n",
上記のように変更し、リンクつけました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Here, the penalty strength set to 5.0 is the penalty for the constraint conditions that arise when converting higher-order interactions to second-order or lower-order interactions. When it is to
In practice, it is difficult to determine how much value to specify. Here we set the value to 5.0 for simplicity.
に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "We want to solve this QUBO with OpenJij's SA, but since OpenJij cannot handle variables that are a mixture of numbers and strings, we need to convert all strings to integers.\n",
OpenJij's simulated annealing
に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "To do so, we use dimod's method label_variables to convert \"1∗2\" and \"aux1,2\" to integers."
For this purpose
に変更し、文末にリンクつけました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "All indices have been converted to integers, and we can solve this QUBO using OpenJij."
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/81501548/202005021-1bf5ef64-b18c-4f67-874c-7f1d88be0c2b.png">
失礼しました。添付画像のようにindicesの方が使われているため、こちらに統一しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "The energy obtained here may not correspond to the original energy of HUBO, depending on the value of strength determined earlier.\n",
the value of penalty strength set at 5.0 earlier.
に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "This can be verified with dimod's ExactPolySolver, which is a solver for exact optimal solutions."
リンクつけました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "## Comparing the results of direct HUBO solving and indirect HUBO solving\n",
上記に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "First, we obtain the energy when using the sample_HUBO method."
失礼しました。上記に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Next, we find the energy by solving using the QUBO transformation.\n",
消しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "We can see that there is quite a difference in this model: solving directly for HUBO yields a lower energy solution.\n",
solving HUBO directly
に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Of course, a more appropriate value of strength could improve the solution by solving for the QUBO transformation, but that is not easy to do."
with
に変更しました。

2022-11-15 20:01 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "The solution method using the QUBO transformation requires preprocessing to convert to QUBO and to determine a parameter called strength.\n",
コード以外のstrengthの部分をpenalty strengthに変更しました。

2022-11-22 10:57 UTC, K-Suzuki-Jij requested changes
細かな修正ありがとうございます。
最後に3点だけ、些細な体裁の修正だけお願いしたいです。
よろしくお願いします🙏

2022-11-22 10:57 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Note that the sample_hubo method can handle non-numeric values as dictionary keys, as shown below."
> Note that the sample_hubo method can

すいません、ここも`sample_hubo`でお願いしたいです🙏

2022-11-22 10:57 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "For this purpose, we use dimod's method relabel_variables to convert \"1∗2\" and \"aux1,2\" to integers [link](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.Samp
> we use dimod's method relabel_variables to convert \"1∗2\" and \"aux1,2\" to integers [link](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.SampleSet.relabel_variables.html).

こちらなんですが、申し訳ありません、リンクは以下のような形で、relabel_variablesに張ってほしいです。

> we use dimod's method [relabel_variables](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.SampleSet.relabel_variables.html) to convert \"1∗2\" and \"aux1,2\" to integers.

2022-11-22 10:57 UTC, K-Suzuki-Jij commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "First, we obtain the energy when using the sample_hubo method."
> we obtain the energy when using the sample_hubo method

こちらも`sample_hubo`としていただきたいです。

2022-12-13 17:55 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "First, we obtain the energy when using the sample_hubo method."
失礼しました、修正しました

2022-12-13 17:55 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "For this purpose, we use dimod's method relabel_variables to convert \"1∗2\" and \"aux1,2\" to integers [link](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/generated/dimod.Samp
修正しました

2022-12-13 17:55 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "Note that the sample_hubo method can handle non-numeric values as dictionary keys, as shown below."
失礼しました、修正しました

2023-01-04 00:41 UTC, K-Suzuki-Jij approved these changes
修正ありがとうございました！

@Jacomichi がOKであればマージしてください！

2023-01-04 02:24 UTC, Jacomichi reviewed
修正ありがとうございます。
自分からは2点だけ確認よろしくお願いいたします。

2023-01-04 02:24 UTC, Jacomichi commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "$$\n",
こちらの数式がうまく表示されていないです。

2023-01-04 02:24 UTC, Jacomichi commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "As shown, in addition to the original variables $\\sigma_1,\\sigma_2,\\sigma_3$, two string variables $\\sigma_{\"1∗2\"}$ and $\\sigma_{\"\\rm aux1,2\"}$ appear. In general, converting HUBO to Q
$\\sigma_{\"1∗2\"}$の添字の中の""は無しにするか、上付きにした方が良いと思います。

上つきの場合は以下のように書いてください
$\\sigma_{\^"1∗2\^"}$

2023-01-18 06:30 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "As shown, in addition to the original variables $\\sigma_1,\\sigma_2,\\sigma_3$, two string variables $\\sigma_{\"1∗2\"}$ and $\\sigma_{\"\\rm aux1,2\"}$ appear. In general, converting HUBO to Q
上付きに修正しました。

2023-01-18 06:30 UTC, mei-maruo commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "$$\n",
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/81501548/213098330-b8cb3366-9181-4f52-aebb-c7a88c329153.png">
手元で確認したところ、表示されているようなのですが、いかがでしょうか？

2023-01-18 06:47 UTC, Jacomichi commented on docs/tutorial/en/002-HuboSolver.ipynb
> +    "$$\n",
おそらく、こちらはgithub上で見ていたことに起因するものであると思いますので、大丈夫です。

2023-01-18 06:47 UTC, Jacomichi approved these changes

2023-01-18 07:31 UTC, merged