Feature/translate 004
OpenJij/OpenJij pull request #337
Opened 2022-11-10 23:33 UTC by mei-maruo

## Changes

- Translated 004 into English

## Related issue

- N/A

## Sample code

- [https://github.com/OpenJij/OpenJij/blob/main/docs/tutorial/ja/004-Evaluation.ipynb](https://github.com/OpenJij/OpenJij/blob/main/docs/tutorial/ja/004-Evaluation.ipynb)

## Destructive changes

- N/A

## Misc

- [この](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R21-R23)説明順を以降での説明順に並び替えました。
- [この](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R192) TTS 計算コードにおけるtauの計算順番を変更しました。
- （※変更はしていません、コメントです。）plotに関して、以下の可能性が考えられるのでは、と危惧しました。
    - あるnum_sweepsの時に、psが0であれば、tau_listにtauが追加されず、plotに失敗する可能性
- [この](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R297-R300)TTSと成功確率のグラフの説明部分において、グラフの順と説明の順が逆だったので、説明の際に、左右の記述を少し追記しました。
- （※変更はしていません、コメントです。）[日本語版](https://github.com/OpenJij/OpenJij/blob/main/docs/tutorial/ja/004-Evaluation.ipynb)での、"補償"は保証のtypoでしょうか？英語版では、"達成"と記述しておきました。([link](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R304))
- [この](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R348-R350) residual energyに関する説明部分を少し自分なりに解釈して英訳しましたのでご確認お願いします。
- [ここ](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R358)以降にて、日本語版では「TTS, 残留エネルギー, 成功確率」の順で書かれていますが、冒頭での記述の順「TTS, 成功確率, 残留エネルギー」に変更しています。図の順も変更しました。
- [この](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R568)部分に、日本語版では、[リンク](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R568)が貼られていましたが、リンク切れのようなので、英語版にはリンクは載せていません。
- [この](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R689)セクションに関して
    - 日本語版では[args](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R676)が改行されていませんでした。
    - 日本語版では[measure_with_energy](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R681)がコード記述になっていませんでした。
    - 日本語版では[residual energy](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R695)の説明に不要な「で」があるようです。
    - 日本語版では[se_lower_tts, se_upper_tts](https://github.com/OpenJij/OpenJij/compare/main...mei-maruo:OpenJij:feature/translate-004?expand=1#diff-ce8cbc18fd8a10b454c1371447a804dd0707f6dc9223f3e16eee3f2e6d044944R705-R709)の説明で上と下が入れ替わっている気がします。（この部分、いまいちわからなかったので、英語版も間違っているかもしれません。ご確認お願いします。）

2022-11-14 07:18 UTC, Jacomichi requested changes
内容確認しました。お手数ですが、確認よろしくお願いいたします。

2022-11-14 07:18 UTC, Jacomichi commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "- se_lower_tts: List of lower errors of TTS\n",
すいません。自分も日本語チュートリアルの中身を正確には理解できませんが、どうやらコードを読むと、se_lower_ttsやse_upper_ttsは成功確率の平均値とその標準偏差から計算される分布の端の方の値を使って計算されたTTSのことのようです。
https://github.com/OpenJij/OpenJij/blob/668020beca6ae1e1d50d32644c490ff202e1d16d/openjij/utils/benchmark.py#L242-L248

ひょっとしたら、説明自体は、doc~stringと同じでもいいかもしれません。
https://github.com/OpenJij/OpenJij/blob/668020beca6ae1e1d50d32644c490ff202e1d16d/openjij/utils/benchmark.py#L52

2022-11-14 07:18 UTC, Jacomichi commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "      The standard deviation of the expected value of success probability for each iteration of annealing\n",
The standard deviation 〜の文章に関して丸々消してもらっていいですか？

上と下でstandard deviationとstandard errorになっており異なっているのは変で、一応、doc stringを信じればstandard errorであるようなので、下の方を文章ごと消してほしいです。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "      The standard deviation of the expected value of success probability for each iteration of annealing\n",
上記記載しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "- se_lower_tts: List of lower errors of TTS\n",
下記と併せて、以下のように変更、で問題ないでしょうか？

> - se_lower_tts: List of lower standard errors of TTS

> - se_upper_tts: List of upper standard errors of TTS

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "    The default is False.\n",
修正しました。同様にexecution_time部分もthe default value is に変えました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "    Reference energy. Used in conjunction with the following `measure_with_energy`. Defaults to `ref_energy = 0`.\n",
修正しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "    This is an optional parameter for the solver. The default is `args = {}`.\n",
修正しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "    This is the value needed to calculate TTS. Equivalent to p_R in the TTS description above.\n",
$p_R$にしました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "    A list of states that will be the ground state (optimal solution). In case of degeneracy (multiple identical states), multiple states should be entered, e.g. [state1, state2].\n",
修正しました。他のground stateもoptimal stateに変更しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "Note that the vertical axis of the success probability diagram above is around that value.\n",
修正しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "The TTS graph on the left shows that it decreases until the annealing time is about 200, i.e., the optimal solution is quickly obtained.\n",
修正しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "In the success probability graph on the right, we see that it increases as the annealing time increases.\n",
修正しました。承知しました、下記のように他のgraph部分は消しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "Most samplers have a key `'execution_time'` that stores the time (in $\\mu$ s) of one execution of each algorithm.\n",
修正しました。失礼しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "Response class returned from `sample_ising` or `sample_qubo` of OpenJij has a member variable `info`.\n",
修正しました。ありがとうございます。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "We solve the Ising model above and see how the TTS and the success probability change as you increase the time per calculation."
修正しました。私もyou 使わない方に賛成です。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "Here we set $J_{ij} \\in [0.1, 1.0]$, $h_0 = -1$, and the other longitudinal magnetic fields to be 0.\n",
修正しました。

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "This is a physical model represented by the following Hamiltonian:\n",
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/81501548/205195136-857e2b7f-fe41-4e62-b796-654e43f147e5.png">
anti-ferromagnetic より antiferromagneticの方が使われているようなので、ハイフンは抜きにしておきます（こちらも検索がうまくできているか自信がありませんが。。。）
単語の説明は、問題を解く上では不要かと思いましたが、以下のように付け加えておきました。いかがでしょうか？
Antiferromagnetic is a magnetism that aligns with neighboring spins pointing in opposite directions.

2022-12-02 03:58 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "> For example, even if a short computation time $\\tau_{short}$ returns a low probability of finding an optimal solution, annealing multiple times with that computation time $\\tau_{short}$ may
修正しました。同様に、`$\tau_{\mathrm{long}}$`に記載を変更しました。

2022-12-02 03:59 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "For more information on dimod's SampleSet, please see dimod's samples page."
追加しました。

2022-12-02 03:59 UTC, mei-maruo commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "- Time to solution (TTS)\n",
後出しの提案で申し訳ないのですが、以下リンクでは、ハイフンで繋げてsolutionのsは小文字となっております。Ngramで確認したら、こちらの方がメジャーなようなので（うまく検索できているか自信ありませんが。。。）、この表記はいかがでしょうか？
https://www.researchgate.net/figure/Time-to-solution-Time-to-solution-TTSt-for-i-traditional-quantum-annealing_fig1_349932739
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/81501548/205191551-bd9ed6bb-f9f3-4491-b590-eedff0f49e15.png">
一旦ハイフン表記で修正していますが、変更した方がよければおっしゃってください。

2022-12-02 05:52 UTC, j-i-k-o commented
> あるnum_sweepsの時に、psが0であれば、tau_listにtauが追加されず、plotに失敗する可能性
こちらに関しては、たしかに成功確率が0であれば仰る通りとなるのですが、今回程度の問題であれば少なくとも1回ぐらいは実行可能解が出てくることを考えるとあまり問題にならない気がします。

他に関しても、Residual Energyの記述に関しても問題ないと思います。

2022-12-06 01:27 UTC, j-i-k-o approved these changes

2022-12-06 02:03 UTC, Jacomichi commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "- Time to solution (TTS)\n",
ハイフンでお願いします！

2022-12-06 02:05 UTC, Jacomichi commented on docs/tutorial/en/004-Evaluation.ipynb
> +    "This is a physical model represented by the following Hamiltonian:\n",
ありがとうございます。
これで大丈夫です！

2023-01-10 08:42 UTC, merged