added the 005 note in English
OpenJij/OpenJij pull request #343
Opened 2022-11-23 21:59 UTC by mei-maruo

## Changes

- Translated 005 into English.

## Related issue

- N/A

## Sample code

- [https://github.com/OpenJij/OpenJij/blob/main/docs/tutorial/ja/005-benchmark_sparse_dense.ipynb](https://github.com/OpenJij/OpenJij/blob/main/docs/tutorial/ja/005-benchmark_sparse_dense.ipynb)

## Destructive changes

- N/A

## Misc

2022-11-25 07:57 UTC, Jacomichi reviewed
PRありがとうございます。
コメントしましたので、確認いただけると幸いです。

2022-11-25 07:57 UTC, Jacomichi commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "The number of nonzero elements in the interaction matrix $J$ of the Ising Hamiltonian or the interaction matrix $Q$ of QUBO can vary greatly depending on the problem.\n",
the interaction matrix $Q$ of QUBO -> QUBO matrix $Q$

2022-11-25 07:57 UTC, Jacomichi commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "The data can, however, not always be represented as a sparse matrix depending on the problem, and in those cases, keeping the data as a sparse matrix will delay computation.\n",
こちら元々の日本語が悪いですね。
「ですが、解きたい問題によっては相互作用行列の多くの要素がnon-zeroの場合もあります。この場合には、疎行列形式のデータ保持では計算速度が低下してしまいます」にしていただけると、ありがたいです。

2022-11-25 07:57 UTC, Jacomichi commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "With `sparse = True`, the internal interaction matrix retains its sparse matrix.\n",
the internal interaction matrix retains its sparse matrix -> the sampler retains the interaction matrix as a sparse matrix
の方がわかりやすい気がしたのですが、どうでしょうか？

2022-11-25 07:57 UTC, Jacomichi commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "Here, we vary the number of spins $n=100,200,500,1000,2000,5000$, and the proportion of elements $p$ in the interaction matrix $J$ is also varied $p=0.1,0.3,0.5,0.8$."
varyよりchangeの方が自然かなと思ったのですが、どうでしょうか？

2022-11-25 07:57 UTC, Jacomichi commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "Furthermore, the dense matrix is faster when $p=0.5,0.8$ is the ratio of elements packed.\n",
Furthermore, the dense matrix is faster when $p=0.5,0.8$で良いと思います。

2022-12-02 05:55 UTC, j-i-k-o commented
タイトルの
> How to preserve the interaction matrix in OpenJij
は、意訳して "Sparse/Dense QUBO matrix in OpenJij" のほうが自然に見えます。

2022-12-05 03:37 UTC, j-i-k-o commented
他に関しては今の所修正点は無いように見えます

2022-12-06 01:30 UTC, j-i-k-o requested changes
タイトルの箇所だけ変更いただきたいです。

2022-12-13 18:56 UTC, mei-maruo commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "Here, we vary the number of spins $n=100,200,500,1000,2000,5000$, and the proportion of elements $p$ in the interaction matrix $J$ is also varied $p=0.1,0.3,0.5,0.8$."
修正しました。

2022-12-13 18:56 UTC, mei-maruo commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "Furthermore, the dense matrix is faster when $p=0.5,0.8$ is the ratio of elements packed.\n",
修正しました。

2022-12-13 18:56 UTC, mei-maruo commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "With `sparse = True`, the internal interaction matrix retains its sparse matrix.\n",
修正しました。

2022-12-13 18:56 UTC, mei-maruo commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "The data can, however, not always be represented as a sparse matrix depending on the problem, and in those cases, keeping the data as a sparse matrix will delay computation.\n",
However, depending on the problem, many elements of the interaction matrix may be non-zero.
In this case, data retention in sparse matrix form will slow down the computation.
としました。

2022-12-13 18:57 UTC, mei-maruo commented on docs/tutorial/en/005-benchmark_sparse_dense.ipynb
> +    "The number of nonzero elements in the interaction matrix $J$ of the Ising Hamiltonian or the interaction matrix $Q$ of QUBO can vary greatly depending on the problem.\n",
修正しました。

> Sparse/Dense QUBO matrix in OpenJij

2023-01-04 06:50 UTC, Jacomichi approved these changes

2023-01-10 08:33 UTC, j-i-k-o approved these changes

2023-01-17 02:45 UTC, merged