Feature/translate-007
OpenJij/OpenJij pull request #345
Opened 2022-12-01 22:47 UTC by mei-maruo

## Changes

- Translated 007 into English.

## Related issue

- N/A

## Sample code

- [https://github.com/OpenJij/OpenJij/tree/main/docs/tutorial/ja/machine_learning](https://github.com/OpenJij/OpenJij/tree/main/docs/tutorial/ja/machine_learning)

## Destructive changes

- N/A

## Misc

- N/A

2022-12-05 11:31 UTC, Jacomichi requested changes
PRありがとうございます。

2022-12-05 11:31 UTC, Jacomichi commented on docs/tutorial/en/machine_learning/clustering.ipynb
> +    "Assuming $n$ is given externally, we divide the given data into $n$ clusters. For simplicity, let us consider 2 clusters in this case."
この定式化だと単純化というより2つのグループへのクラスタリングしかできないので、For simplicity,はない方がいいと思います。

2022-12-05 11:31 UTC, Jacomichi commented on docs/tutorial/en/machine_learning/clustering.ipynb
> +    "# !pip install jijmodeling-transpiler"
このセルは消してしまっても大丈夫かなと思います。
ただ、「モデリングにはJijModeling、QUBOの生成にはJijModeling Transpilerを使います」のような最適化で最初に行っていた文章を追加しておいていただきたいです。

2022-12-05 11:31 UTC, Jacomichi commented on docs/tutorial/en/machine_learning/clustering.ipynb
> +    "With the mathematical model and data, let us start solving the problem by Openjij."
少しだけ、JijModeling Transpilerを使う旨の説明を足していただいてもよろしいですか？

2022-12-05 11:31 UTC, Jacomichi commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "The PyQUBO model is created by `to_pyqubo` with the `problem` created by JijModeling and the `instance_data` we set to a value as arguments. Next, we compile it into a QUBO model that can be com
software → solver

2022-12-05 11:31 UTC, Jacomichi commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "print('Accuracy of QBoost is {}'.format(max(accs_test_oj)))"
元々のpredictorよりも良くなっていることを示すために、
作った20個のweak predictorの平均の正答率みたいなものも表示させることは可能ですか？

2022-12-13 22:44 UTC, 29rou approved these changes

2022-12-15 17:48 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "The PyQUBO model is created by `to_pyqubo` with the `problem` created by JijModeling and the `instance_data` we set to a value as arguments. Next, we compile it into a QUBO model that can be com
修正しました。

2022-12-15 17:48 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/clustering.ipynb
> +    "# !pip install jijmodeling-transpiler"
消して、以下の文を追加しました。
We use JijModeling for modeling and JijModeling Transpiler for QUBO generation.

2022-12-15 17:48 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/clustering.ipynb
> +    "Assuming $n$ is given externally, we divide the given data into $n$ clusters. For simplicity, let us consider 2 clusters in this case."
消しました。

2022-12-20 19:20 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "print('Accuracy of QBoost is {}'.format(max(accs_test_oj)))"
すみません、コメントしたつもりができていなかったようです。
https://github.com/OpenJij/OpenJij/pull/345/files#diff-fa1210f1d17b64535aec5d5aaa30fce1b149f742c25e05ff78d9ff399e134ab0R350
こちらでいかがでしょうか？自信がないので、ご確認お願いします。

2022-12-21 04:17 UTC, maqid commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "instance_data = {'y': y_train, 'c': y_pred_list_train, 'lam': lam, 'y_train': y_train, 'y_test': y_test, 'y_pred_list_test': y_pred_list_test}"
y_train': y_train, 'y_test': y_test, 'y_pred_list_test': y_pred_list_testは不要かと思います。
```python
instance_data = {'y': y_train, 'c': y_pred_list_train, 'lam': lam}
```

2022-12-21 04:17 UTC, maqid commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "pyq_model, pyq_chache = to_pyqubo(problem, instance_data, {})\n",
pyq_chache -> pyq_cacheに修正て頂きたいです。

2022-12-21 04:17 UTC, maqid commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "result = pyq_chache.decode(response)"
pyq_chache -> pyq_cacheに修正て頂きたいです。

2022-12-21 04:17 UTC, maqid commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "from sklearn import metrics\n",
一行開けて頂きたいです。

2022-12-21 04:17 UTC, maqid commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "accs_ave = sum(accs)/20\n",
以下のように修正して頂きたいです。（PEP8 コーディングスタイルより）
```python
accs_ave = sum(accs) / 20
```

2023-01-03 23:08 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "instance_data = {'y': y_train, 'c': y_pred_list_train, 'lam': lam, 'y_train': y_train, 'y_test': y_test, 'y_pred_list_test': y_pred_list_test}"
QBoostのaccuracyを計算する際にy_train, y_test, y_pred_list_testは必要だと思うのですが、いかがでしょう？

2023-01-03 23:08 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/clustering.ipynb
> +    "instance_data = {'d':distance_matrix(df1, df1)}"
修正しました。

2023-01-03 23:08 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/clustering.ipynb
> +    "from jijmodeling.transpiler.pyqubo.to_pyqubo import to_pyqubo"
修正しました。

2023-01-03 23:08 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "pyq_model, pyq_chache = to_pyqubo(problem, instance_data, {})\n",
修正しました。

2023-01-03 23:09 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "result = pyq_chache.decode(response)"
修正しました。

2023-01-03 23:09 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "from sklearn import metrics\n",
修正しました。

2023-01-03 23:09 UTC, mei-maruo commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "accs_ave = sum(accs)/20\n",
修正しました。

2023-01-04 07:29 UTC, Jacomichi commented on docs/tutorial/en/machine_learning/qboost.ipynb
> +    "print('Accuracy of QBoost is {}'.format(max(accs_test_oj)))"
オッケーだと思います！

2023-01-04 07:29 UTC, Jacomichi approved these changes

2023-01-10 07:59 UTC, maqid approved these changes

2023-01-17 03:45 UTC, merged